
  public $queries_reading = array (
  'aixada_account' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'deposit_for_uf',
    4 => 'uf_weekly_balance',
    5 => 'initialize_caixa',
    7 => 'income_spending_balance',
    8 => 'ufs_with_negative_balance',
    9 => 'aixada_account_list_all_query',
  ),
  'aixada_currency' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'aixada_account_list_all_query',
    3 => 'aixada_currency_list_all_query',
  ),
  'aixada_payment_method' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'aixada_account_list_all_query',
    3 => 'aixada_payment_method_list_all_query',
  ),
  'aixada_user' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'check_credentials',
    3 => 'check_password',
    4 => 'get_members_of_uf',
    5 => 'find_user_by_login_or_email',
    6 => 'register_user',
    7 => 'update_user',
    8 => 'get_member_info',
    9 => 'member_id_of_user_id',
    10 => 'users_without_ufs',
    12 => 'latest_incidents',
    13 => 'todays_incidents',
    14 => 'users_without_uf',
    15 => 'users_without_member',
    16 => 'get_users',
    17 => 'get_active_roles',
    18 => 'aixada_user_list_all_query',
  ),
  'aixada_member' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'get_members_of_uf',
    3 => 'create_member',
    4 => 'get_member_info',
    6 => 'member_id_of_user_id',
    7 => 'latest_incidents',
    8 => 'todays_incidents',
    9 => 'get_users',
    10 => 'get_active_users_for_role',
    11 => 'get_inactive_users_for_role',
    12 => 'summarized_orders_for_date',
    13 => 'aixada_member_list_all_query',
    14 => 'aixada_user_list_all_query',
  ),
  'aixada_uf' => 
  array (
    0 => 'latest_movements',
    1 => 'negative_accounts',
    2 => 'find_uf_by_name',
    3 => 'create_uf',
    5 => 'update_uf',
    6 => 'get_all_ufs',
    7 => 'users_without_ufs',
    8 => 'get_users',
    9 => 'summarized_orders_for_date',
    10 => 'detailed_orders_for_provider_and_date',
    11 => 'detailed_preorders_for_provider_and_date',
    12 => 'active_times',
    13 => 'get_ufs_for_validation',
    14 => 'get_active_ufs',
    15 => 'aixada_distributor_list_all_query',
    16 => 'aixada_favorite_order_cart_list_all_query',
    17 => 'aixada_favorite_order_item_list_all_query',
    18 => 'aixada_member_list_all_query',
    19 => 'aixada_order_item_list_all_query',
    20 => 'aixada_product_list_all_query',
    21 => 'aixada_provider_list_all_query',
    22 => 'aixada_shop_item_list_all_query',
    23 => 'aixada_uf_list_all_query',
    24 => 'aixada_user_list_all_query',
  ),
  'aixada_account_balance' => 
  array (
    0 => 'negative_accounts',
    1 => 'deduct_stock_and_pay',
    2 => 'undo_validate',
  ),
  'aixada_product_orderable_for_date' => 
  array (
    0 => 'get_next_equal_shop_date',
    1 => 'providers_with_active_products_for_order',
    2 => 'product_categories_for_order',
    3 => 'products_for_order_by_provider',
    4 => 'products_for_order_by_category',
    5 => 'products_for_order_like',
    6 => 'get_activated_products',
    7 => 'providers_with_active_products_for_shop',
    8 => 'product_categories_for_shop',
    9 => 'products_for_shop_by_provider',
    10 => 'products_for_shop_by_category',
    11 => 'products_for_shop_like',
    12 => 'get_ufs_for_validation',
    13 => 'products_for_validate_like',
    14 => 'aixada_product_orderable_for_date_list_all_query',
  ),
  'aixada_shopping_dates' => 
  array (
    0 => 'shopping_dates',
    1 => 'aixada_shopping_dates_list_all_query',
  ),
  'aixada_user_role' => 
  array (
    0 => 'get_members_of_uf',
    1 => 'get_member_info',
    2 => 'get_active_roles',
    3 => 'get_active_users_for_role',
    4 => 'get_inactive_users_for_role',
    6 => 'aixada_user_role_list_all_query',
  ),
  'aixada_provider' => 
  array (
    0 => 'get_member_info',
    1 => 'latest_incidents',
    2 => 'todays_incidents',
    3 => 'providers_with_active_products_for_order',
    4 => 'product_categories_for_order',
    5 => 'products_for_order_by_provider',
    6 => 'products_for_order_by_category',
    7 => 'products_for_order_like',
    8 => 'products_for_order_by_date',
    9 => 'products_for_favorite_order',
    10 => 'list_preorder_providers',
    11 => 'preorderable_products',
    12 => 'list_all_providers_short',
    13 => 'list_all_ordered_providers_short',
    14 => 'total_orders_for_date_and_provider',
    15 => 'providers_with_orders_for_date',
    16 => 'summarized_orders_for_date',
    17 => 'summarized_preorders',
    18 => 'detailed_total_orders_for_date',
    19 => 'spending_per_provider',
    20 => 'shopped_items_by_id',
    21 => 'shop_for_uf_and_time',
    22 => 'providers_with_active_products_for_shop',
    23 => 'product_categories_for_shop',
    24 => 'products_for_shop_by_provider',
    25 => 'products_for_shop_by_category',
    26 => 'products_for_shop_like',
    27 => 'products_for_shopping',
    28 => 'provider_weekly_orders',
    29 => 'products_for_validating',
    30 => 'products_for_validate_like',
    31 => 'products_below_min_stock',
    32 => 'aixada_product_list_all_query',
    33 => 'aixada_provider_list_all_query',
    34 => 'aixada_providers_of_distributor_list_all_query',
    35 => 'aixada_user_list_all_query',
  ),
  'aixada_product' => 
  array (
    0 => 'get_member_info',
    1 => 'providers_with_active_products_for_order',
    2 => 'product_categories_for_order',
    3 => 'products_for_order_by_provider',
    4 => 'products_for_order_by_category',
    5 => 'products_for_order_like',
    6 => 'products_for_order_by_date',
    7 => 'products_for_favorite_order',
    8 => 'list_preorder_providers',
    9 => 'list_preorder_products',
    10 => 'preorderable_products',
    11 => 'list_all_providers_short',
    12 => 'list_all_ordered_providers_short',
    13 => 'get_activated_products',
    14 => 'get_deactivated_products',
    15 => 'get_arrived_products',
    16 => 'get_not_arrived_products',
    17 => 'add_stock',
    18 => 'total_orders_for_date_and_provider',
    19 => 'providers_with_orders_for_date',
    20 => 'summarized_orders_for_provider_and_date',
    21 => 'detailed_orders_for_provider_and_date',
    22 => 'detailed_preorders_for_provider_and_date',
    23 => 'detailed_total_orders_for_date',
    24 => 'spending_per_provider',
    25 => 'shopped_items_by_id',
    26 => 'shop_for_uf_and_time',
    27 => 'providers_with_active_products_for_shop',
    28 => 'product_categories_for_shop',
    29 => 'products_for_shop_by_provider',
    30 => 'products_for_shop_by_category',
    31 => 'products_for_shop_like',
    32 => 'products_for_shopping',
    33 => 'most_bought_products',
    34 => 'least_bought_products',
    35 => 'uf_weekly_orders',
    36 => 'provider_weekly_orders',
    37 => 'product_weekly_orders',
    38 => 'products_for_validating',
    39 => 'products_for_validate_like',
    40 => 'products_below_min_stock',
    41 => 'aixada_favorite_order_item_list_all_query',
    42 => 'aixada_order_item_list_all_query',
    43 => 'aixada_product_list_all_query',
    44 => 'aixada_product_orderable_for_date_list_all_query',
    45 => 'aixada_shop_item_list_all_query',
    46 => 'aixada_stock_movement_list_all_query',
  ),
  'aixada_incident' => 
  array (
    0 => 'latest_incidents',
    1 => 'todays_incidents',
    2 => 'aixada_incident_list_all_query',
  ),
  'aixada_incident_type' => 
  array (
    0 => 'latest_incidents',
    1 => 'todays_incidents',
    2 => 'get_incident_types',
    3 => 'aixada_incident_list_all_query',
    4 => 'aixada_incident_type_list_all_query',
  ),
  'aixada_product_category' => 
  array (
    0 => 'product_categories_for_order',
    1 => 'product_categories_for_shop',
    2 => 'aixada_product_list_all_query',
    3 => 'aixada_product_category_list_all_query',
  ),
  'aixada_rev_tax_type' => 
  array (
    0 => 'products_for_order_by_provider',
    1 => 'products_for_order_by_category',
    2 => 'products_for_order_like',
    3 => 'products_for_order_by_date',
    4 => 'products_for_favorite_order',
    5 => 'preorderable_products',
    6 => 'shopped_items_by_id',
    7 => 'shop_for_uf_and_time',
    8 => 'products_for_shop_by_provider',
    9 => 'products_for_shop_by_category',
    10 => 'products_for_shop_like',
    11 => 'products_for_shopping',
    12 => 'products_for_validating',
    13 => 'products_for_validate_like',
    14 => 'aixada_product_list_all_query',
    15 => 'aixada_rev_tax_type_list_all_query',
  ),
  'aixada_unit_measure' => 
  array (
    0 => 'products_for_order_by_provider',
    1 => 'products_for_order_by_category',
    2 => 'products_for_order_like',
    3 => 'products_for_order_by_date',
    4 => 'preorderable_products',
    5 => 'summarized_orders_for_provider_and_date',
    6 => 'detailed_orders_for_provider_and_date',
    7 => 'detailed_preorders_for_provider_and_date',
    8 => 'detailed_total_orders_for_date',
    9 => 'shopped_items_by_id',
    10 => 'shop_for_uf_and_time',
    11 => 'products_for_shop_by_provider',
    12 => 'products_for_shop_by_category',
    13 => 'products_for_shop_like',
    14 => 'products_for_shopping',
    15 => 'products_for_validating',
    16 => 'products_for_validate_like',
    17 => 'aixada_product_list_all_query',
    19 => 'aixada_unit_measure_list_all_query',
  ),
  'aixada_order_item' => 
  array (
    0 => 'products_for_order_by_date',
    1 => 'make_favorite_order_cart',
    2 => 'move_all_orders',
    3 => 'list_preorder_providers',
    4 => 'list_preorder_products',
    5 => 'list_all_ordered_providers_short',
    6 => 'get_not_arrived_products',
    7 => 'orders_for_date_and_provider',
    8 => 'total_orders_for_date_and_provider',
    9 => 'providers_with_orders_for_date',
    10 => 'summarized_orders_for_date',
    11 => 'summarized_orders_for_provider_and_date',
    12 => 'summarized_preorders',
    13 => 'detailed_orders_for_provider_and_date',
    14 => 'detailed_preorders_for_provider_and_date',
    15 => 'detailed_total_orders_for_date',
    16 => 'spending_per_provider',
    17 => 'convert_order_to_shop',
    18 => 'most_bought_products',
    19 => 'least_bought_products',
    20 => 'uf_weekly_orders',
    21 => 'provider_weekly_orders',
    22 => 'product_weekly_orders',
    23 => 'aixada_order_item_list_all_query',
  ),
  'aixada_favorite_order_item' => 
  array (
    0 => 'products_for_favorite_order',
    1 => 'aixada_favorite_order_item_list_all_query',
  ),
  'aixada_shop_item' => 
  array (
    0 => 'move_all_orders',
    3 => 'get_arrived_products',
    4 => 'get_not_arrived_products',
    5 => 'last_shop_times_for_uf',
    6 => 'nonvalidated_shop_times_for_uf',
    7 => 'future_shop_times_for_uf',
    8 => 'past_validated_shop_times_for_uf',
    9 => 'shopped_items_by_id',
    10 => 'shop_for_uf_and_time',
    11 => 'products_for_shopping',
    12 => 'get_ufs_for_validation',
    13 => 'products_for_validating',
    14 => 'dates_with_unvalidated_shop_carts',
    15 => 'validated_shop_carts',
    16 => 'undo_validate',
    18 => 'aixada_shop_item_list_all_query',
  ),
  'aixada_stock_movement' => 
  array (
    0 => 'stock_movements',
    1 => 'aixada_stock_movement_list_all_query',
  ),
  'aixada_distributor' => 
  array (
    0 => 'aixada_distributor_list_all_query',
    1 => 'aixada_providers_of_distributor_list_all_query',
  ),
  'aixada_favorite_order_cart' => 
  array (
    0 => 'aixada_favorite_order_cart_list_all_query',
    1 => 'aixada_favorite_order_item_list_all_query',
  ),
  'aixada_orderable_type' => 
  array (
    0 => 'aixada_orderable_type_list_all_query',
    1 => 'aixada_product_list_all_query',
  ),
  'aixada_providers_of_distributor' => 
  array (
    0 => 'aixada_providers_of_distributor_list_all_query',
  ),
);