
  public $queries_reading = array (
  'aixada_account' => 
  array (
    0 => 'negative_accounts',
    1 => 'account_extract',
    2 => 'latest_movements',
    3 => 'deposit_for_uf',
    5 => 'uf_weekly_balance',
    6 => 'validate_shop_cart',
    7 => 'initialize_caixa',
    9 => 'income_spending_balance',
    10 => 'aixada_account_list_all_query',
  ),
  'aixada_currency' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'aixada_account_list_all_query',
    3 => 'aixada_currency_list_all_query',
  ),
  'aixada_payment_method' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'aixada_account_list_all_query',
    3 => 'aixada_payment_method_list_all_query',
  ),
  'aixada_user' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'check_credentials',
    3 => 'check_password',
    4 => 'get_members_of_uf',
    5 => 'find_user_by_login_or_email',
    6 => 'register_user',
    7 => 'update_user',
    8 => 'get_member_info',
    9 => 'member_id_of_user_id',
    10 => 'users_without_ufs',
    12 => 'latest_incidents',
    13 => 'todays_incidents',
    14 => 'users_without_uf',
    15 => 'users_without_member',
    16 => 'get_users',
    17 => 'get_active_roles',
    18 => 'aixada_user_list_all_query',
  ),
  'aixada_member' => 
  array (
    0 => 'account_extract',
    1 => 'latest_movements',
    2 => 'get_members_of_uf',
    3 => 'create_member',
    4 => 'get_member_info',
    6 => 'member_id_of_user_id',
    7 => 'latest_incidents',
    8 => 'todays_incidents',
    9 => 'get_users',
    10 => 'get_active_users_for_role',
    11 => 'get_inactive_users_for_role',
    12 => 'summarized_orders_for_date',
    13 => 'aixada_member_list_all_query',
    14 => 'aixada_user_list_all_query',
  ),
  'aixada_uf' => 
  array (
    0 => 'latest_movements',
    1 => 'find_uf_by_name',
    2 => 'create_uf',
    4 => 'update_uf',
    5 => 'get_all_ufs',
    6 => 'users_without_ufs',
    7 => 'get_users',
    8 => 'summarized_orders_for_date',
    9 => 'detailed_orders_for_provider_and_date',
    10 => 'detailed_preorders_for_provider_and_date',
    11 => 'active_times',
    12 => 'get_active_ufs',
    13 => 'aixada_distributor_list_all_query',
    14 => 'aixada_favorite_order_cart_list_all_query',
    15 => 'aixada_favorite_order_item_list_all_query',
    16 => 'aixada_member_list_all_query',
    17 => 'aixada_order_item_list_all_query',
    18 => 'aixada_product_list_all_query',
    19 => 'aixada_provider_list_all_query',
    20 => 'aixada_shop_item_list_all_query',
    21 => 'aixada_uf_list_all_query',
    22 => 'aixada_user_list_all_query',
  ),
  'aixada_cart' => 
  array (
    0 => 'get_shop_cart',
    1 => 'dates_with_unvalidated_shop_carts',
    2 => 'activate_preorder_products',
    5 => 'get_purchase_listing',
    6 => 'get_ufs_for_validation',
    8 => 'validate_shop_cart',
  ),
  'aixada_order_item' => 
  array (
    0 => 'get_order_cart',
    1 => 'get_ordered_products_list',
    2 => 'set_order_item_status',
    5 => 'activate_preorder_products',
    8 => 'list_preorder_providers',
    9 => 'list_preorder_products',
    10 => 'move_all_orders',
    11 => 'get_orderable_products_for_dates',
    12 => 'orders_for_date_and_provider',
    14 => 'total_orders_for_date_and_provider',
    15 => 'providers_with_orders_for_date',
    16 => 'summarized_orders_for_date',
    17 => 'summarized_orders_for_provider_and_date',
    18 => 'summarized_preorders',
    19 => 'detailed_orders_for_provider_and_date',
    20 => 'detailed_preorders_for_provider_and_date',
    21 => 'detailed_total_orders_for_date',
    22 => 'spending_per_provider',
    23 => 'most_bought_products',
    24 => 'least_bought_products',
    25 => 'uf_weekly_orders',
    26 => 'provider_weekly_orders',
    27 => 'product_weekly_orders',
    28 => 'aixada_order_item_list_all_query',
  ),
  'aixada_product_orderable_for_date' => 
  array (
    0 => 'get_orderable_dates',
    1 => 'activate_preorder_products',
    2 => 'repeat_orderable_day_provider',
    3 => 'toggle_orderable_product',
    4 => 'get_orderable_products_for_dates',
    5 => 'aixada_product_orderable_for_date_list_all_query',
  ),
  'aixada_user_role' => 
  array (
    0 => 'get_members_of_uf',
    1 => 'get_member_info',
    2 => 'get_active_roles',
    3 => 'get_active_users_for_role',
    4 => 'get_inactive_users_for_role',
    6 => 'aixada_user_role_list_all_query',
  ),
  'aixada_provider' => 
  array (
    0 => 'get_member_info',
    1 => 'latest_incidents',
    2 => 'todays_incidents',
    3 => 'activate_preorder_products',
    4 => 'list_preorder_providers',
    5 => 'get_orderable_providers',
    6 => 'get_orderable_providers_for_date',
    7 => 'get_shop_providers_for_date',
    9 => 'get_stock_providers',
    10 => 'get_all_active_providers',
    11 => 'get_orderable_categories_for_date',
    12 => 'get_shop_categories_for_date',
    14 => 'total_orders_for_date_and_provider',
    15 => 'providers_with_orders_for_date',
    16 => 'summarized_orders_for_date',
    17 => 'summarized_preorders',
    18 => 'detailed_total_orders_for_date',
    19 => 'spending_per_provider',
    20 => 'shopped_items_by_id',
    21 => 'shop_for_uf_and_time',
    22 => 'provider_weekly_orders',
    23 => 'aixada_product_list_all_query',
    24 => 'aixada_provider_list_all_query',
    25 => 'aixada_providers_of_distributor_list_all_query',
    26 => 'aixada_user_list_all_query',
  ),
  'aixada_product' => 
  array (
    0 => 'get_member_info',
    1 => 'activate_preorder_products',
    3 => 'list_preorder_providers',
    4 => 'list_preorder_products',
    5 => 'repeat_orderable_day_provider',
    6 => 'repeat_orderable_product',
    7 => 'toggle_orderable_product',
    8 => 'get_type_orderable_products',
    9 => 'get_preorderable_products',
    10 => 'add_stock',
    11 => 'total_orders_for_date_and_provider',
    12 => 'providers_with_orders_for_date',
    13 => 'summarized_orders_for_provider_and_date',
    14 => 'detailed_orders_for_provider_and_date',
    15 => 'detailed_preorders_for_provider_and_date',
    16 => 'detailed_total_orders_for_date',
    17 => 'spending_per_provider',
    18 => 'shopped_items_by_id',
    19 => 'shop_for_uf_and_time',
    20 => 'most_bought_products',
    21 => 'least_bought_products',
    22 => 'uf_weekly_orders',
    23 => 'provider_weekly_orders',
    24 => 'product_weekly_orders',
    25 => 'products_below_min_stock',
    26 => 'aixada_favorite_order_item_list_all_query',
    27 => 'aixada_order_item_list_all_query',
    28 => 'aixada_product_list_all_query',
    29 => 'aixada_product_orderable_for_date_list_all_query',
    30 => 'aixada_shop_item_list_all_query',
    31 => 'aixada_stock_movement_list_all_query',
  ),
  'aixada_incident' => 
  array (
    0 => 'latest_incidents',
    1 => 'todays_incidents',
    2 => 'aixada_incident_list_all_query',
  ),
  'aixada_incident_type' => 
  array (
    0 => 'latest_incidents',
    1 => 'todays_incidents',
    2 => 'get_incident_types',
    3 => 'aixada_incident_list_all_query',
    4 => 'aixada_incident_type_list_all_query',
  ),
  'aixada_order_to_shop' => 
  array (
    0 => 'set_order_item_status',
    1 => 'activate_preorder_products',
  ),
  'aixada_order' => 
  array (
    0 => 'activate_preorder_products',
    1 => 'get_orderable_products_for_dates',
  ),
  'aixada_shop_item' => 
  array (
    0 => 'move_all_orders',
    3 => 'last_shop_times_for_uf',
    4 => 'shopped_items_by_id',
    5 => 'shop_for_uf_and_time',
    6 => 'get_purchase_listing',
    7 => 'undo_validate',
    9 => 'aixada_shop_item_list_all_query',
  ),
  'aixada_stock_movement' => 
  array (
    0 => 'stock_movements',
    1 => 'aixada_stock_movement_list_all_query',
  ),
  'aixada_unit_measure' => 
  array (
    0 => 'summarized_orders_for_provider_and_date',
    1 => 'detailed_orders_for_provider_and_date',
    2 => 'detailed_preorders_for_provider_and_date',
    3 => 'detailed_total_orders_for_date',
    4 => 'shopped_items_by_id',
    5 => 'shop_for_uf_and_time',
    6 => 'aixada_product_list_all_query',
    8 => 'aixada_unit_measure_list_all_query',
  ),
  'aixada_rev_tax_type' => 
  array (
    0 => 'shopped_items_by_id',
    1 => 'shop_for_uf_and_time',
    2 => 'aixada_product_list_all_query',
    3 => 'aixada_rev_tax_type_list_all_query',
  ),
  'aixada_account_balance' => 
  array (
    0 => 'undo_validate',
  ),
  'aixada_distributor' => 
  array (
    0 => 'aixada_distributor_list_all_query',
    1 => 'aixada_providers_of_distributor_list_all_query',
  ),
  'aixada_favorite_order_cart' => 
  array (
    0 => 'aixada_favorite_order_cart_list_all_query',
    1 => 'aixada_favorite_order_item_list_all_query',
  ),
  'aixada_favorite_order_item' => 
  array (
    0 => 'aixada_favorite_order_item_list_all_query',
  ),
  'aixada_orderable_type' => 
  array (
    0 => 'aixada_orderable_type_list_all_query',
    1 => 'aixada_product_list_all_query',
  ),
  'aixada_product_category' => 
  array (
    0 => 'aixada_product_list_all_query',
    1 => 'aixada_product_category_list_all_query',
  ),
  'aixada_providers_of_distributor' => 
  array (
    0 => 'aixada_providers_of_distributor_list_all_query',
  ),
  'aixada_shopping_dates' => 
  array (
    0 => 'aixada_shopping_dates_list_all_query',
  ),
);