
  public $queries_reading = array (
  'aixada_account' => 
  array (
    0 => 'correct_account_balance',
    1 => 'get_account_balance',
    2 => 'global_accounts_balance',
    5 => 'negative_accounts',
    6 => 'get_extract_in_range',
    7 => 'latest_movements',
    8 => 'deposit',
    12 => 'income_spending_balance',
    13 => 'correct_stock',
    14 => 'uf_weekly_balance',
    15 => 'validate_shop_cart',
    16 => 'aixada_account_list_all_query',
  ),
  'aixada_currency' => 
  array (
    0 => 'latest_movements',
    1 => 'aixada_currency_list_all_query',
  ),
  'aixada_payment_method' => 
  array (
    0 => 'latest_movements',
    1 => 'aixada_payment_method_list_all_query',
  ),
  'aixada_user' => 
  array (
    0 => 'latest_movements',
    1 => 'new_user_member',
    2 => 'check_password',
    3 => 'users_without_ufs',
    5 => 'users_without_uf',
    6 => 'users_without_member',
    7 => 'member_id_of_user_id',
    8 => 'check_credentials',
    9 => 'update_user',
    10 => 'get_users',
    11 => 'get_active_roles',
    12 => 'aixada_user_list_all_query',
  ),
  'aixada_member' => 
  array (
    0 => 'latest_movements',
    1 => 'summarized_orders_for_date',
    2 => 'get_member_listing',
    3 => 'get_member_info',
    4 => 'get_unassigned_members',
    5 => 'search_members',
    7 => 'member_id_of_user_id',
    8 => 'get_users',
    9 => 'get_active_users_for_role',
    10 => 'get_inactive_users_for_role',
    11 => 'aixada_member_list_all_query',
    12 => 'aixada_user_list_all_query',
  ),
  'aixada_uf' => 
  array (
    0 => 'latest_movements',
    1 => 'summarized_orders_for_date',
    2 => 'detailed_orders_for_provider_and_date',
    3 => 'detailed_preorders_for_provider_and_date',
    4 => 'get_purchase_listing',
    6 => 'active_times',
    7 => 'create_uf',
    10 => 'users_without_ufs',
    11 => 'get_users',
    12 => 'get_uf_listing_cart_count',
    13 => 'aixada_cart_list_all_query',
    14 => 'aixada_member_list_all_query',
    15 => 'aixada_order_item_list_all_query',
    16 => 'aixada_order_to_shop_list_all_query',
    17 => 'aixada_product_list_all_query',
    18 => 'aixada_provider_list_all_query',
    19 => 'aixada_uf_list_all_query',
    20 => 'aixada_user_list_all_query',
  ),
  'aixada_cart' => 
  array (
    0 => 'get_shop_cart',
    1 => 'dates_with_unvalidated_shop_carts',
    2 => 'get_detailed_order_info',
    3 => 'activate_preorder_products',
    5 => 'get_non_validated_carts',
    7 => 'get_ufs_for_validation',
    9 => 'validate_shop_cart',
    10 => 'aixada_cart_list_all_query',
    11 => 'aixada_order_item_list_all_query',
    12 => 'aixada_shop_item_list_all_query',
  ),
  'aixada_order_item' => 
  array (
    0 => 'get_order_cart',
    1 => 'get_ordered_products_list',
    3 => 'set_order_status',
    5 => 'set_order_item_status',
    6 => 'activate_preorder_products',
    11 => 'list_preorder_providers',
    12 => 'list_preorder_products',
    13 => 'get_orderable_products_for_dates',
    14 => 'orders_for_date_and_provider',
    15 => 'total_orders_for_date_and_provider',
    16 => 'providers_with_orders_for_date',
    17 => 'summarized_orders_for_date',
    18 => 'summarized_orders_for_provider_and_date',
    19 => 'summarized_preorders',
    20 => 'detailed_orders_for_provider_and_date',
    21 => 'detailed_preorders_for_provider_and_date',
    22 => 'detailed_total_orders_for_date',
    23 => 'spending_per_provider',
    24 => 'most_bought_products',
    25 => 'least_bought_products',
    26 => 'uf_weekly_orders',
    27 => 'provider_weekly_orders',
    28 => 'product_weekly_orders',
    29 => 'aixada_order_item_list_all_query',
  ),
  'aixada_product_orderable_for_date' => 
  array (
    0 => 'get_orderable_dates',
    1 => 'repeat_orderable_day_provider',
    2 => 'toggle_orderable_product',
    3 => 'get_orderable_products_for_dates',
    4 => 'aixada_product_orderable_for_date_list_all_query',
  ),
  'aixada_incident_type' => 
  array (
    0 => 'get_incident_types',
    1 => 'aixada_incident_list_all_query',
    2 => 'aixada_incident_type_list_all_query',
  ),
  'aixada_shop_item' => 
  array (
    0 => 'get_detailed_order_info',
    1 => 'last_shop_times_for_uf',
    2 => 'shopped_items_by_id',
    3 => 'shop_for_uf_and_time',
    4 => 'get_purchase_listing',
    5 => 'undo_validate',
    7 => 'aixada_shop_item_list_all_query',
  ),
  'aixada_order' => 
  array (
    0 => 'get_detailed_order_info',
    1 => 'activate_preorder_products',
    2 => 'get_orderable_products_for_dates',
    3 => 'aixada_order_list_all_query',
  ),
  'aixada_provider' => 
  array (
    0 => 'get_detailed_order_info',
    1 => 'activate_preorder_products',
    2 => 'list_preorder_providers',
    3 => 'get_orderable_providers',
    4 => 'get_orderable_providers_for_date',
    5 => 'get_shop_providers_for_date',
    7 => 'get_stock_providers',
    8 => 'get_all_active_providers',
    9 => 'get_orderable_categories_for_date',
    10 => 'get_shop_categories_for_date',
    12 => 'total_orders_for_date_and_provider',
    13 => 'providers_with_orders_for_date',
    14 => 'summarized_orders_for_date',
    15 => 'summarized_preorders',
    16 => 'detailed_total_orders_for_date',
    17 => 'spending_per_provider',
    18 => 'shopped_items_by_id',
    19 => 'shop_for_uf_and_time',
    20 => 'provider_weekly_orders',
    21 => 'aixada_order_list_all_query',
    22 => 'aixada_product_list_all_query',
    23 => 'aixada_provider_list_all_query',
    24 => 'aixada_user_list_all_query',
  ),
  'aixada_order_to_shop' => 
  array (
    0 => 'set_order_status',
    1 => 'activate_preorder_products',
    4 => 'aixada_order_to_shop_list_all_query',
  ),
  'aixada_product' => 
  array (
    0 => 'set_order_status',
    2 => 'activate_preorder_products',
    5 => 'list_preorder_providers',
    6 => 'list_preorder_products',
    7 => 'repeat_orderable_day_provider',
    8 => 'repeat_orderable_product',
    9 => 'toggle_orderable_product',
    10 => 'get_type_orderable_products',
    11 => 'get_preorderable_products',
    12 => 'correct_stock',
    14 => 'add_stock',
    15 => 'products_below_min_stock',
    16 => 'total_orders_for_date_and_provider',
    17 => 'providers_with_orders_for_date',
    18 => 'summarized_orders_for_provider_and_date',
    19 => 'detailed_orders_for_provider_and_date',
    20 => 'detailed_preorders_for_provider_and_date',
    21 => 'detailed_total_orders_for_date',
    22 => 'spending_per_provider',
    23 => 'shopped_items_by_id',
    24 => 'shop_for_uf_and_time',
    25 => 'most_bought_products',
    26 => 'least_bought_products',
    27 => 'uf_weekly_orders',
    28 => 'provider_weekly_orders',
    29 => 'product_weekly_orders',
    30 => 'aixada_order_item_list_all_query',
    31 => 'aixada_order_to_shop_list_all_query',
    32 => 'aixada_product_list_all_query',
    33 => 'aixada_shop_item_list_all_query',
    34 => 'aixada_stock_movement_list_all_query',
  ),
  'aixada_stock_movement' => 
  array (
    0 => 'stock_movements',
    1 => 'aixada_stock_movement_list_all_query',
  ),
  'aixada_unit_measure' => 
  array (
    0 => 'summarized_orders_for_provider_and_date',
    1 => 'detailed_orders_for_provider_and_date',
    2 => 'detailed_preorders_for_provider_and_date',
    3 => 'detailed_total_orders_for_date',
    4 => 'shopped_items_by_id',
    5 => 'shop_for_uf_and_time',
    6 => 'aixada_product_list_all_query',
    8 => 'aixada_unit_measure_list_all_query',
  ),
  'aixada_rev_tax_type' => 
  array (
    0 => 'shopped_items_by_id',
    1 => 'shop_for_uf_and_time',
    2 => 'aixada_product_list_all_query',
    3 => 'aixada_rev_tax_type_list_all_query',
  ),
  'aixada_user_role' => 
  array (
    0 => 'get_active_roles',
    1 => 'get_active_users_for_role',
    2 => 'get_inactive_users_for_role',
    4 => 'aixada_user_role_list_all_query',
  ),
  'aixada_account_balance' => 
  array (
    0 => 'undo_validate',
  ),
  'aixada_incident' => 
  array (
    0 => 'aixada_incident_list_all_query',
  ),
  'aixada_iva_type' => 
  array (
    0 => 'aixada_iva_type_list_all_query',
    1 => 'aixada_product_list_all_query',
  ),
  'aixada_orderable_type' => 
  array (
    0 => 'aixada_orderable_type_list_all_query',
    1 => 'aixada_product_list_all_query',
  ),
  'aixada_product_category' => 
  array (
    0 => 'aixada_product_list_all_query',
    1 => 'aixada_product_category_list_all_query',
  ),
  'aixada_shopping_dates' => 
  array (
    0 => 'aixada_shopping_dates_list_all_query',
  ),
);